#!/bin/sh

bspc monitor -d 1 2 3 4 5

bspc config border_width         4
bspc config window_gap           24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Emacs" state=tiled
